sudo: false

language: node_js
node_js:
  - "15"
os:
  - linux
  - windows

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run ci-lint; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run test; else npm run ci-test; fi
  - npm run check

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

deploy:
  provider: script
  script: |
    # Creates a tarball for the package
    npm pack
  skip_cleanup: true

notifications:
    webhooks:
        urls:
          - "https://webhooks.gitter.im/e/3569d7edff0d38f93cd7"
        on_success: always
        on_failure: always
        on_start: always
